#!/usr/bin/env python3
"""Import a DMOJ user-data ZIP into this competitive-programming repository.

Usage:
    python tools/import_dmoj.py /path/to/username-data.zip

Behavior:
- keeps only Accepted (AC) submissions;
- keeps the newest AC for each problem code;
- preserves source bytes exactly;
- names files by DMOJ problem code;
- removes files generated by the previous run using .dmoj_manifest.json;
- regenerates metadata.csv and SOLUTIONS.md.
"""

from __future__ import annotations

import csv
import json
import re
import sys
import zipfile
from collections import Counter
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOLUTIONS = ROOT / "solutions"
MANIFEST = ROOT / ".dmoj_manifest.json"


def parse_date(s: str) -> datetime:
    return datetime.fromisoformat(s.replace("Z", "+00:00"))


def classify_problem(code: str) -> str:
    c = code.lower()
    if re.match(r"^ccc", c): return "CCC"
    if re.match(r"^cco", c): return "CCO"
    if c.startswith("coci"): return "COCI"
    if c.startswith("dmopc"): return "DMOPC"
    if c.startswith("dmpg"): return "DMPG"
    if c.startswith("dwite"): return "DWITE"
    if c.startswith("ecoo"): return "ECOO"
    if c.startswith("ioi"): return "IOI"
    if c.startswith("usaco"): return "USACO"
    if c.startswith("oly"): return "Olympiads_School"
    if re.fullmatch(r"dp[a-z]", c): return "AtCoder_DP"
    return "Other"


def safe_code(code: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", code)


def choose_latest(info: dict) -> dict[str, tuple[str, dict]]:
    latest = {}
    for sid, meta in info.items():
        if meta.get("result") != "AC":
            continue
        p = meta["problem"]
        if p not in latest:
            latest[p] = (sid, meta)
            continue
        old_sid, old = latest[p]
        if (parse_date(meta["date"]), int(sid)) > (parse_date(old["date"]), int(old_sid)):
            latest[p] = (sid, meta)
    return latest


def old_generated_paths() -> list[Path]:
    if not MANIFEST.exists():
        return []
    try:
        data = json.loads(MANIFEST.read_text(encoding="utf-8"))
        return [ROOT / p for p in data.get("generated_files", [])]
    except Exception:
        return []


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("Usage: python tools/import_dmoj.py /path/to/username-data.zip")

    export = Path(sys.argv[1]).expanduser().resolve()
    if not export.exists():
        raise SystemExit(f"File not found: {export}")

    with zipfile.ZipFile(export) as z:
        if "submissions/info.json" not in z.namelist():
            raise SystemExit("This ZIP does not contain submissions/info.json")
        info = json.loads(z.read("submissions/info.json"))
        src = {}
        for name in z.namelist():
            m = re.fullmatch(r"submissions/(\d+)(\.[^/]+)", name)
            if m:
                src[m.group(1)] = (name, m.group(2))

        latest = choose_latest(info)

        # Only remove files previously generated by this importer.
        for old in old_generated_paths():
            try:
                if old.is_file():
                    old.unlink()
            except OSError:
                pass

        rows = []
        generated = []
        for problem, (sid, meta) in sorted(latest.items()):
            if sid not in src:
                print(f"warning: no source file for submission {sid} ({problem})")
                continue
            member, ext = src[sid]
            category = classify_problem(problem)
            rel = Path("solutions") / category / f"{safe_code(problem)}{ext}"
            dest = ROOT / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_bytes(z.read(member))
            generated.append(rel.as_posix())
            rows.append({
                "problem": problem,
                "category": category,
                "source": rel.as_posix(),
                "submission_id": sid,
                "date": meta.get("date", ""),
                "language": meta.get("language", ""),
                "result": meta.get("result", ""),
                "time_seconds": meta.get("time", ""),
                "memory_kb": meta.get("memory", ""),
                "dmoj_url": f"https://dmoj.ca/problem/{problem}",
            })

    with (ROOT / "metadata.csv").open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    generated.append("metadata.csv")

    counts = Counter(r["category"] for r in rows)
    lang_counts = Counter(r["language"] for r in rows)

    lines = [
        "# Solution Index", "",
        f"**{len(rows)}** unique accepted DMOJ problems. For problems with multiple AC submissions, this repository keeps the most recent AC.", "",
    ]
    for category in sorted(counts):
        lines += [f"## {category} ({counts[category]})", "", "| Problem | Source | Language |", "|---|---|---|"]
        for r in sorted((x for x in rows if x["category"] == category), key=lambda x: x["problem"].lower()):
            src_link = r["source"].replace(" ", "%20")
            lines.append(f"| [{r['problem']}]({r['dmoj_url']}) | [{Path(r['source']).name}]({src_link}) | {r['language']} |")
        lines.append("")
    (ROOT / "SOLUTIONS.md").write_text("\n".join(lines), encoding="utf-8")
    generated.append("SOLUTIONS.md")

    manifest = {
        "source_export": export.name,
        "unique_problems": len(rows),
        "generated_files": sorted(generated),
        "category_counts": dict(sorted(counts.items())),
        "language_counts": dict(sorted(lang_counts.items())),
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    print(f"Imported {len(rows)} unique accepted problems from {len(info)} accepted submissions.")
    print("Categories:", ", ".join(f"{k}={v}" for k, v in sorted(counts.items())))


if __name__ == "__main__":
    main()
